version: "3"
services:
    mkdocs:
        container_name: mkdocs
        build:
            context: .
            dockerfile: ./mkdocs/Dockerfile
        ports:
            - 8000:8000
        volumes:
            - ./src:/docs
